source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_terraform', '~> 1.21'
gem 'rake_docker', '~> 2.11'
gem 'rake_circle_ci', '~> 0.9'
gem 'rake_github', '~> 0.5'
gem 'rake_ssh', '~> 0.4'
gem 'rake_gpg', '~> 0.12'
gem 'git', '~> 1.10'
gem 'os', '~> 1.1'
gem 'rspec', '~> 3.11'
gem 'docker-api', '~> 1.34'
gem 'serverspec', '~> 2.42'
gem 'aws-sdk', '~> 3'
gem 'semantic', '~> 1.6'
gem 'octopoller', '~> 0.1'
gem 'dotenv', '~> 2.1'
