version: 2.1
jobs:
  test:
    working_directory: ~/source
    docker:
      - image: docker:19.03-git
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/ci/common/install-bash.sh
      - run: ./scripts/ci/common/install-ruby.sh
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-docker-compose.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/steps/test.sh
  prerelease:
    working_directory: ~/source
    docker:
      - image: docker:19.03-git
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/ci/common/install-bash.sh
      - run: ./scripts/ci/common/install-ruby.sh
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/steps/prerelease.sh
  release:
    working_directory: ~/source
    docker:
      - image: docker:19.03-git
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/ci/common/install-bash.sh
      - run: ./scripts/ci/common/install-ruby.sh
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/steps/release.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - prerelease:
          requires:
          - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
          - prerelease
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master
